platform :ios, '10.0'
use_frameworks!
target 'QuickFile' do
    pod 'SwiftMessages'
    pod 'MJRefresh'
    pod 'M13ProgressSuite'
    pod 'Firebase/Core'
    pod 'Firebase/Database'
    pod 'Firebase/Auth'
    pod 'Firebase/Crash'
    pod 'Firebase/Performance'
    pod 'Firebase/Messaging'
    pod 'DownloadButton'
    pod 'GoogleSignIn'
    pod 'KeychainAccess'
    pod 'ReachabilitySwift'
    pod 'MarqueeLabel/Swift'
    pod 'DZNEmptyDataSet'
    pod 'SwiftyBeaver'
    pod 'Reqres'
    pod 'Reflection'
    pod 'SwiftyTimer'
    pod 'SwiftLint'
end
